language: python
python: "2.7"

sudo: required
services:
  - docker

branches:
  only:
    - master
    - dev

env:
  - IMAGE_OS=centos7
  - TEST_SUITE=integration

script:
  - docker build -t ansible --no-cache -f $IMAGE_OS/Dockerfile

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
